/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as RootRouteRouteImport } from './routes/_root/route'
import { Route as RootIndexRouteImport } from './routes/_root/index'
import { Route as RootTimelineIndexRouteImport } from './routes/_root/timeline/index'
import { Route as RootTasksIndexRouteImport } from './routes/_root/tasks/index'
import { Route as RootShedulerIndexRouteImport } from './routes/_root/sheduler/index'
import { Route as RootShareIndexRouteImport } from './routes/_root/share/index'
import { Route as RootSettingsIndexRouteImport } from './routes/_root/settings/index'
import { Route as RootHelpIndexRouteImport } from './routes/_root/help/index'
import { Route as RootChatIndexRouteImport } from './routes/_root/chat/index'
import { Route as RootTasksSerialNumberIndexRouteImport } from './routes/_root/tasks/$serialNumber/index'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RootRouteRoute = RootRouteRouteImport.update({
  id: '/_root',
  getParentRoute: () => rootRouteImport,
} as any)
const RootIndexRoute = RootIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RootRouteRoute,
} as any)
const RootTimelineIndexRoute = RootTimelineIndexRouteImport.update({
  id: '/timeline/',
  path: '/timeline/',
  getParentRoute: () => RootRouteRoute,
} as any)
const RootTasksIndexRoute = RootTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => RootRouteRoute,
} as any)
const RootShedulerIndexRoute = RootShedulerIndexRouteImport.update({
  id: '/sheduler/',
  path: '/sheduler/',
  getParentRoute: () => RootRouteRoute,
} as any)
const RootShareIndexRoute = RootShareIndexRouteImport.update({
  id: '/share/',
  path: '/share/',
  getParentRoute: () => RootRouteRoute,
} as any)
const RootSettingsIndexRoute = RootSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => RootRouteRoute,
} as any)
const RootHelpIndexRoute = RootHelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => RootRouteRoute,
} as any)
const RootChatIndexRoute = RootChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => RootRouteRoute,
} as any)
const RootTasksSerialNumberIndexRoute =
  RootTasksSerialNumberIndexRouteImport.update({
    id: '/tasks/$serialNumber/',
    path: '/tasks/$serialNumber/',
    getParentRoute: () => RootRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRoute
  '/': typeof RootIndexRoute
  '/chat': typeof RootChatIndexRoute
  '/help': typeof RootHelpIndexRoute
  '/settings': typeof RootSettingsIndexRoute
  '/share': typeof RootShareIndexRoute
  '/sheduler': typeof RootShedulerIndexRoute
  '/tasks': typeof RootTasksIndexRoute
  '/timeline': typeof RootTimelineIndexRoute
  '/tasks/$serialNumber': typeof RootTasksSerialNumberIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/': typeof RootIndexRoute
  '/chat': typeof RootChatIndexRoute
  '/help': typeof RootHelpIndexRoute
  '/settings': typeof RootSettingsIndexRoute
  '/share': typeof RootShareIndexRoute
  '/sheduler': typeof RootShedulerIndexRoute
  '/tasks': typeof RootTasksIndexRoute
  '/timeline': typeof RootTimelineIndexRoute
  '/tasks/$serialNumber': typeof RootTasksSerialNumberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_root': typeof RootRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_root/': typeof RootIndexRoute
  '/_root/chat/': typeof RootChatIndexRoute
  '/_root/help/': typeof RootHelpIndexRoute
  '/_root/settings/': typeof RootSettingsIndexRoute
  '/_root/share/': typeof RootShareIndexRoute
  '/_root/sheduler/': typeof RootShedulerIndexRoute
  '/_root/tasks/': typeof RootTasksIndexRoute
  '/_root/timeline/': typeof RootTimelineIndexRoute
  '/_root/tasks/$serialNumber/': typeof RootTasksSerialNumberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/'
    | '/chat'
    | '/help'
    | '/settings'
    | '/share'
    | '/sheduler'
    | '/tasks'
    | '/timeline'
    | '/tasks/$serialNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/chat'
    | '/help'
    | '/settings'
    | '/share'
    | '/sheduler'
    | '/tasks'
    | '/timeline'
    | '/tasks/$serialNumber'
  id:
    | '__root__'
    | '/_root'
    | '/auth'
    | '/_root/'
    | '/_root/chat/'
    | '/_root/help/'
    | '/_root/settings/'
    | '/_root/share/'
    | '/_root/sheduler/'
    | '/_root/tasks/'
    | '/_root/timeline/'
    | '/_root/tasks/$serialNumber/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RootRouteRoute: typeof RootRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_root': {
      id: '/_root'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RootRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_root/': {
      id: '/_root/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RootIndexRouteImport
      parentRoute: typeof RootRouteRoute
    }
    '/_root/timeline/': {
      id: '/_root/timeline/'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof RootTimelineIndexRouteImport
      parentRoute: typeof RootRouteRoute
    }
    '/_root/tasks/': {
      id: '/_root/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof RootTasksIndexRouteImport
      parentRoute: typeof RootRouteRoute
    }
    '/_root/sheduler/': {
      id: '/_root/sheduler/'
      path: '/sheduler'
      fullPath: '/sheduler'
      preLoaderRoute: typeof RootShedulerIndexRouteImport
      parentRoute: typeof RootRouteRoute
    }
    '/_root/share/': {
      id: '/_root/share/'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof RootShareIndexRouteImport
      parentRoute: typeof RootRouteRoute
    }
    '/_root/settings/': {
      id: '/_root/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof RootSettingsIndexRouteImport
      parentRoute: typeof RootRouteRoute
    }
    '/_root/help/': {
      id: '/_root/help/'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof RootHelpIndexRouteImport
      parentRoute: typeof RootRouteRoute
    }
    '/_root/chat/': {
      id: '/_root/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof RootChatIndexRouteImport
      parentRoute: typeof RootRouteRoute
    }
    '/_root/tasks/$serialNumber/': {
      id: '/_root/tasks/$serialNumber/'
      path: '/tasks/$serialNumber'
      fullPath: '/tasks/$serialNumber'
      preLoaderRoute: typeof RootTasksSerialNumberIndexRouteImport
      parentRoute: typeof RootRouteRoute
    }
  }
}

interface RootRouteRouteChildren {
  RootIndexRoute: typeof RootIndexRoute
  RootChatIndexRoute: typeof RootChatIndexRoute
  RootHelpIndexRoute: typeof RootHelpIndexRoute
  RootSettingsIndexRoute: typeof RootSettingsIndexRoute
  RootShareIndexRoute: typeof RootShareIndexRoute
  RootShedulerIndexRoute: typeof RootShedulerIndexRoute
  RootTasksIndexRoute: typeof RootTasksIndexRoute
  RootTimelineIndexRoute: typeof RootTimelineIndexRoute
  RootTasksSerialNumberIndexRoute: typeof RootTasksSerialNumberIndexRoute
}

const RootRouteRouteChildren: RootRouteRouteChildren = {
  RootIndexRoute: RootIndexRoute,
  RootChatIndexRoute: RootChatIndexRoute,
  RootHelpIndexRoute: RootHelpIndexRoute,
  RootSettingsIndexRoute: RootSettingsIndexRoute,
  RootShareIndexRoute: RootShareIndexRoute,
  RootShedulerIndexRoute: RootShedulerIndexRoute,
  RootTasksIndexRoute: RootTasksIndexRoute,
  RootTimelineIndexRoute: RootTimelineIndexRoute,
  RootTasksSerialNumberIndexRoute: RootTasksSerialNumberIndexRoute,
}

const RootRouteRouteWithChildren = RootRouteRoute._addFileChildren(
  RootRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  RootRouteRoute: RootRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
